#include<stdio.h>
#include<stdlib.h>
structnode
{
intkey;
structnode*llink;
structnode*rlink;
};
typedefstructnode*nodepointer;
voidinsert(intitem,nodepointerhead)
{
nodepointertemp;
temp=(nodepointer)malloc(sizeof(structnode));
temp->key=item;
temp->llink=head;
temp->rlink=head->rlink;
head->rlink->llink=temp;
head->rlink=temp;
head=temp;
}
intdel(intitem,nodepointerhead)
{
if(head==NULL)
{
printf("EMPTYLIST:Noelementtobedeleted\n");
return0;
}
head=head->rlink;
if((head)->key==-1)

{
printf("Cannotdeleteheadernode\n");
returnitem;
}
while((head)->key!=-1)
{
if((head)->key==item)
{
printf("Elementdeleted:%d",item);
if(head->rlink)
(head->llink)->rlink=head->rlink;
if(head->llink)
(head->rlink)->llink=head->llink;
returnitem;
}
head=head->rlink;
}
printf("Elementnotfound\n");
return0;
}
voiddisplayr(nodepointerhead)
{
head=head->rlink;
if(head==NULL)
{
printf("EMPTYLSIT\n");
return;
}
while((head->rlink)->key!=-1)
{
printf("%d\t",head->key);
head=head->rlink;
}
if(head->key!=-1)
printf("%d\n",head->key);
else
printf("EMPTYLIST\n");
}
voiddisplayf(nodepointerhead)
{
head=head->llink;
if(head==NULL)
{
printf("EMPTYLSIT\n");
return;
}
while((head->llink)->key!=-1)
{
printf("%d\t",head->key);
head=head->llink;

}
printf("%d\n",head->key);
}
intmain()
{
intch,element;
nodepointerfirst;
first=(nodepointer)malloc(sizeof(structnode));
first->key=-1;
first->llink=first;
first->rlink=first;
intcopy;
while(1)
{
printf("\nEnter\n1.Insert\n2.Delete\n3.DisplayForward\n4.Display

Backward\n5.Close\n");
scanf("%d",&ch);
switch(ch)
{
case1:printf("enterelementtobeinserted\n");

scanf("%d",&element);
insert(element,first);
break;

case2:printf("Enterelementtobedeleted\n");
scanf("%d",&element);
del(element,first);
break;

case3:printf("Listis\n");
displayf(first);
break;
case4:printf("Listis\n");
displayr(first);
break;
case5:printf("Closing\n");
exit(0);
}
}
}
