#include<stdio.h>
#include<stdio.h>
typedefenumprecedence
{lparen,rparen,plus,minus,multipy,divide,mod,eos,operand}precedence;
intisp[]={0,19,12,12,13,13,13,0};
inticp[]={20,19,12,12,13,13,13,0};
charexpr[100];
intstack[100];
inttop=-1;
precedencegetToken(char*symbol,int*n)
{
*symbol=expr[(*n)++];
switch(*symbol)
{
case'(':returnlparen;
case')':returnrparen;
case'+':returnplus;
case'-':returnminus;
case'*':returnmultipy;
case'/':returndivide;
case'%':returnmod;
case'':returneos;
case'\0':returneos;
default:returnoperand;
}
}
voidprintToken(precedencetoken)
{
switch(token)
{
caselparen:printf("(");
break;
caserparen:printf(")");
break;
caseplus:printf("+");

break;
caseminus:printf("-");
break;
casemultipy:printf("*");
break;
casedivide:printf("/");
break;
casemod:printf("%%");
break;
caseeos:printf("");
break;

case8:break;
}
}
voidpush(inttoken)
{
stack[++top]=token;
}
intpop()
{
returnstack[top--];
}
voidpostfix(void)
{
charsymbol;
precedencetoken;
intn=0;
top=0;
stack[0]=eos;
for(token=getToken(&symbol,&n);token!=eos;token=getToken(&symbol,&n))
{
if(token==operand)
printf("%c",symbol);
elseif(token==rparen)
{
while(stack[top]!=lparen)
printToken(pop());
pop();
}
else
{
while(isp[stack[top]]>=icp[token])
printToken(pop());
push(token);
}
}
while((token=pop())!=eos)
printToken(token);
printf("\n");
}

intmain()
{
printf("enterexpr\n");
scanf("%s",expr);
postfix();
}
